--DROP TABLE IF EXISTS BOOKING;
CREATE TABLE IF NOT EXISTS BOOKING (
id INT PRIMARY KEY,
first_name VARCHAR(250) NOT NULL,
last_name VARCHAR(250) NOT NULL,
dob VARCHAR(10) NOT NULL,
checkin_datetime VARCHAR(23) NOT NULL,
checkout_datetime VARCHAR(23) NOT NULL,
total_price DECIMAL(20, 2),
deposit DECIMAL(20, 2),
line1 VARCHAR(250) NOT NULL,
line2 VARCHAR(250),
city VARCHAR(250) NOT NULL,
state VARCHAR(250) NOT NULL,
zip_code INT(6) NOT NULL
);